stages:
    - build-azure
    - build-public
    - build
    - deploy
build-azure:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - name: docker:dind
  script:
    - docker login -u $AZURE_REGISTRY_USER -p $AZURE_REGISTRY_PASSWORD $AZURE_REGISTRY_URL
    - docker build -t $AZURE_REGISTRY_URL/portfolio:$CI_COMMIT_REF_SLUG . 
    - docker push $AZURE_REGISTRY_URL/portfolio:$CI_COMMIT_REF_SLUG



